// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClusterOverviewResponse = { bootstrapServers: string, totalTopics: number, totalPartitions: number, preferredPartitionLeaderPercentage: number, totalUnderReplicatedPartitions: number, };
