// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublishMessageRequest = { key: string, payload: string, headers: Array<PublishMessageHeader> | null, };

export type PublishMessageHeader = { key: string, value: string | null, };
