// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { TopicConfig } from './TopicConfig'

export type TopicSummary = {
  topic: string,
  partitions: number,
  preferredLeaderPercent: number,
  underReplicated: number,
  customConfigs: number,
  configs: Array<TopicConfig>
}
